version: "3.9"
services:
  api:
    build: .
    command: make start
    ports:
      - "0.0.0.0:8000:8000"
    volumes:
      - .:/usr/src/app
    # This is useful to connect a debuger to the container
    stdin_open: true
    tty: true
